name: CI
on:
    - push
    - pull_request
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - run: curl -fsSL https://git.io/shellspec | sh -s -- --yes
            - run: shellspec
